name: Actions

on:
  push:
    branches:
      - master
      - rel/*
      - staging
      - trying
    tags:
      - r*
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - master
      - rel/*
    paths-ignore:
      - "**/*.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: npm i

      - name: Run tests
        run: npm run test
