name: Actions

on:
  push:
    branches:
      - main
      - rel/*
      - staging
      - trying
    tags:
      - r*
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - main
      - rel/*
    paths-ignore:
      - "**/*.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install dependencies
        run: npm i

      - name: Rum compile
        run: npm run compile

      - name: Run tests
        run: npm run test
